<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helper/helper.proto

namespace GPBMetadata\Helper;

class Helper
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a1368656c7065722f68656c7065722e70726f746f120668656c70" .
            "657222180a09496452657175657374120b0a036e756d180120012805221c" .
            "0a0a4964526573706f6e7365120e0a06726573756c741801200128033246" .
            "0a0648656c706572123c0a0f47657444697374726962757465496412112e" .
            "68656c7065722e4964526571756573741a122e68656c7065722e49645265" .
            "73706f6e7365280130014214ca02114d6963726f50726f746f5c48656c70" .
            "6572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

